name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # Setup SSH agent with private key from secrets
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    # Add EC2 host to known_hosts
    - name: Add EC2 Host to known_hosts
      run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    # Deploy to EC2
    - name: Deploy to EC2
      run: |
        ssh ubuntu@${{ secrets.EC2_HOST }} '
          cd /var/www/html/devops_demo
          git pull origin main
        '

    - name: Deployment Successful
      run: echo "ðŸš€ Deployment completed successfully!"
